### ISSUE TITLE
Code is running but there is no backend modules are working only a gui is displaying. None of the event handling buttons are working. 

### ISSUE THREAD

**Issue by dilipcm** [Ronald-Saunfe/PMV-music-player#1]
Exception in thread Thread-1:
 Traceback (most recent call last):
   File "C:\Users\Dilip C M\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
     self.run()
   File "C:\Users\Dilip C M\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
     self._target(*self._args, **self._kwargs)
   File "main.py", line 301, in load_tracks
     for filename in file_names:
 UnboundLocalError: local variable 'file_names' referenced before assignment

**Comment by Ronald-Saunfe** [comment]
There is the scope of the project for now... feel free to add more features
